exclude: ['README.md']
timezone: US/Eastern
papers:
  - layout: paper
    year: 2017
    paper-type: inproceedings
    img: ICIOT2016
    title: An energy-aware and under-SLA-constraints VM consolidation strategy based on the optimal matching method
    authors: Weiling Li, <span class="color-blue">Yongbo Wang</span>, Yuandou Wang, Yunni Xia, Kunyin Guo, Quanwang Wu, Qingsheng Zhu
    booktitle: International Journal of Web Services Research Volume 14, Issue 4 (<strong>IJWSR</strong>)
    booktitle-url: 
    venue: workshop
  - layout: paper
    year: 2016
    paper-type: inproceedings
    img: ICIOT2016
    title: "Stochastic performance analysis of unreliable IaaS clouds"
    authors: <span class="color-blue">YongBuo Wang</span>, HaiChuan Zhang, KunYin Guo, Yunni Xia*, WeiLing Li
    booktitle: "Proceedings of S2 International Conference on Internet of Things (<strong>ICIOT</strong>)"
    booktitle-url: papers/Stochastic performance analysis of unreliable IaaS clouds.pdf
    doc-url: papers/Stochastic performance analysis of unreliable IaaS clouds.pdf
    venue: workshop
    abstract: >
      Performance evaluation of cloud data-centers has drawn considerable attention from academy and industry. In this study, we present an analytical approach to the performance analysis of Infrastructure-as-a-Service cloud data-centers with unreliable task executions and resubmissions of unsuccessful tasks. Several performance metrics are considered and analyzed under variable load intensities, failure frequencies, multiplexing abilities, and service intensities. We also conduct a case study based on a real-world cloud data-center and employ a confidence interval check to validate the correctness of the proposed model. 